homeDir=/usr/local/tomcat/data
parser=org.jamwiki.parser.jflex.JFlexParser
props-initialized=true
wiki-version=1.4.0
file-dir-full-path=/usr/local/tomcat/data/files
file-dir-relative-path=/files/
file-upload-storage=DOCROOT
search-engine=org.jamwiki.search.LuceneSearchEngine
server-url=http\://localhost:8888
shared-upload-virtual-wiki=test
driver=org.hsqldb.jdbcDriver
database-type=org.jamwiki.db.HSqlQueryHandler
db-user=sa
db-password=""
url=jdbc:hsqldb:file:/database/jamwikidb;shutdown=true