/**
 * Licensed under the GNU LESSER GENERAL PUBLIC LICENSE, version 2.1, dated February 1999.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the latest version of the GNU Lesser General
 * Public License as published by the Free Software Foundation;
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program (LICENSE.txt); if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 *
 * Based on code generated by Agitar build: Agitator Version 1.0.2.000071 (Build date: Jan 12, 2007) [1.0.2.000071]
 */
package org.jamwiki.parser;

import org.jamwiki.JAMWikiUnitTest;
import org.junit.Test;
import static org.assertj.core.api.Assertions.assertThat;
import org.jamwiki.model.Namespace;

public class WikiLinkTest extends JAMWikiUnitTest {

	@Test
	public void testConstructor() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		assertThat(wikiLink.getQuery()).isNull();;
		assertThat(wikiLink.getSection()).isNull();;
		assertThat(wikiLink.getText()).isNull();;
		assertThat(wikiLink.getArticle()).isNull();;
		assertThat(Namespace.namespace(Namespace.MAIN_ID)).isEqualTo(wikiLink.getNamespace());
		assertThat(wikiLink.getDestination()).isNull();;
		assertThat(wikiLink.getColon()).isFalse();
	}

	@Test
	public void testSetArticle() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setArticle("testWikiLinkArticle");
		assertThat("testWikiLinkArticle").isEqualTo(wikiLink.getArticle());
	}

	@Test
	public void testSetColon() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setColon(true);
		assertThat(wikiLink.getColon()).isTrue();
	}

	@Test
	public void testSetDestination() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en", "testWikiLinkDestination");
		assertThat("testWikiLinkDestination").isEqualTo(wikiLink.getDestination());
	}

	@Test
	public void testSetNamespace() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setNamespace(Namespace.namespace(Namespace.FILE_ID));
		assertThat(Namespace.namespace(Namespace.FILE_ID)).isEqualTo(wikiLink.getNamespace());
	}

	@Test(expected=IllegalArgumentException.class)
	public void testSetNamespace2() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setNamespace(null);
		assertThat(Namespace.namespace(Namespace.FILE_ID)).isEqualTo(wikiLink.getNamespace());
	}

	@Test
	public void testSetQuery() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setQuery("testWikiLinkQuery");
		assertThat("testWikiLinkQuery").isEqualTo(wikiLink.getQuery());
	}

	@Test
	public void testSetSection() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setSection("testWikiLinkSection");
		assertThat("testWikiLinkSection").isEqualTo(wikiLink.getSection());
	}

	@Test
	public void testSetText() throws Throwable {
		WikiLink wikiLink = new WikiLink("/wiki", "en");
		wikiLink.setText("testWikiLinkText");
		assertThat("testWikiLinkText").isEqualTo(wikiLink.getText());
	}
}

